# Classification according the Ne II, Ne III and Ne V emission lines information - Download the Photometry Tables for each object found

From the objects that we find in NED with Ne emission lines, now we are going to classify according to what information the Ne II, Ne III and Ne V emission lines each have.

Also inside the main loop, for each object found in NED with Ne emission lines, we will save the photometry tables in a .csv file.

In [1]:
from datetime import date
import time
import pandas as pd
import numpy as np
import csv

from pathlib import Path
from astropy.table import Table

import astropy.units as u
from astropy.table import hstack

In [2]:
path_raw = '../Datos/Raw/'
Path(path_raw).mkdir(parents=True, exist_ok=True) #If the folder doesn't exist, then it will be created
path_phot_ned = '../Datos/Phot_Tables_NED/' #In this path wi will save the photometry tables for each object
Path(path_phot_ned).mkdir(parents=True, exist_ok=True)

In [3]:
date_samples = 'Apr_01_2022'

In [14]:
df = pd.read_csv(path_raw+'Obj_Ne-IR_'+date_samples+'.csv')
df

,Name_Id,Id_used_NED,RA,DEC,otype_txt,redshift,rvz_type,otypes,SMB_sample
0,3C 234.0,3C 234.0,150.456345,28.785818,Sy1,0.18494,z,AGN|G |IR |QSO|Rad|Sy1|X |blu|gam,283
1,M 84,M 84,186.265597,12.886983,Sy2,0.00327,z,* |AGN|G |GiC|GiG|IR |Rad|Sy2|UV |X |smm,414
2,2MASS J13000535+1632148,NVSS J130005+163212,195.022283,16.537433,Sy1,0.07993,z,AGN|G |IR |Rad|Sy1|X,428
3,NGC 262,NGC 262,12.196426,31.956957,Sy2,0.015260233939595302,v,* |AGN|Bla|G |GiG|IR |QSO|Rad|Sy2|X |gam,484
4,IRAS 04385-0828,IRAS 04385-0828,70.229004,-8.372813,Sy2,0.015064,z,* |AGN|G |GiG|IR |Sy2,541
...,...,...,...,...,...,...,...,...,...
354,NGC 3982,NGC 3982,179.117269,55.125239,Sy1,0.00371,z,AGN|G |GiG|HI |IR |Rad|Sy1|X,43595
355,PSCz Q18368+3549,IRAS 18368+3549,279.647646,35.872153,Sy2,0.11617,z,AGN|G |IR |Mas|Sy2,43670
356,Mrk 622,Mrk 622,121.920816,39.004235,Sy2,0.02335,z,AGN|G |IR |LIN|Rad|Sy2|X,43765
357,[LGE2006] 12,[LGE2006] 12,163.000458,57.406528,Sy1,0.974,z,AGN|G |IR |Rad|Sy1|X |smm,43819
358,2MASX J14323249+3406257,2MASX J14323249+3406257,218.135416,34.107058,Sy2,0.0424,z,* |AG?|AGN|EmG|G |Sy2,44215

The wavelenght for NeII, NeIII and NeV in the infrared spectrum are 12.8 microns, 15.6 microns and 14.3 microns respectively. This values are equivalents to the following frequencies which are related to different labels of "Observed Passband" in NED database as we ilustrate in the next list:

* Frequency: 1.92e+13 Hz: [NeIII] 15.6 microns
* Frecuency: 1.93e+13 Hz: [Ne III] 15.56 (IRS), [NeIII] 15.6 Spitzer, [Ne III] (Spitzer), [Ne III] 15.5 (IRS)
* Frecuency: 2.09e+13 Hz: [Ne V] 14.32 (IRS), [Ne V] 14.32 Spitzer, [Ne V] 14.32, [Ne V] 14.3 Spitzer, [Ne V] 14.3 microns
* Frequency: 2.10e+13 Hz: [Ne V] 14.3 (IRS)
* Frequency: 2.34e+13 Hz: [Ne II] 12.81 (IRS), [Ne II] 12.8 Spitzer, [Ne II] 12.8 (IRS), [Ne II] 12.81, NEII (VLT), 12.81 microns (VLT) 

In the variable **Ne_IR_Fq** we define a list with the those frequency values

In [15]:
Ne_IR_Fq = [19200000000000.0,19300000000000.0,20900000000000.0,21000000000000.0,23400000000000.0]

In [17]:
NeII_NeIII_NeV_IR_obj = [] #List of objects with NeII, NeIII and NeV data
NeII_NeIII_IR_obj = [] #List of objects with NeII and NeIII data
NeII_NeV_IR_obj = [] #List of objects with NeII and NeV data
NeIII_NeV_IR_obj = [] #List of objects with NeIII and NeV data
NeIII_IR_obj = [] #List of objects with NeIII data
NeV_IR_obj = [] #List of objects with NeV data
NeII_IR_obj = [] #List of objects with NeII data

#We create and open a file .csv to write the list of objects names with Ne_IR data
outfile = open(path_raw+'Obj_Ne-IR_v2_'+date_samples+'.csv','w')
writer = csv.writer(outfile) # create the csv writer
header = ['Name_Id','id_from','RA','DEC','otype_txt','redshift','rvz_type','otypes','Ne_IR_info','SMB_sample']#Creating header
writer.writerow(header) #Writing the header

start = time.time()
for ind, name in enumerate(df['Name_Id']):
    phot_t = Table.read(path_phot_ned+name+'_NED_phot_tables'+'.vot', 
                      format='votable')
    
    Fr=phot_t['Frequency'] #We get the Frequency column from the table
   
    if (Ne_IR_Fq[0] in Fr or Ne_IR_Fq[1] in Fr) and (Ne_IR_Fq[2] in Fr or Ne_IR_Fq[3] in Fr) and Ne_IR_Fq[4] in Fr:
        print(f"{ind}, {name}, NeII, NeIII and NeV")
        #Writing the object names
        outstring = [name,df['Id_used_NED'][ind],df['RA'][ind],df['DEC'][ind],df['otype_txt'][ind],df['redshift'][ind],
                     df['rvz_type'][ind],df['otypes'][ind],'NeII|NeIII|NeV',df['SMB_sample'][ind]]
        writer.writerow(outstring) #write the data
        NeII_NeIII_NeV_IR_obj.append(name) #Save the object name in the list NeII_NeIII_NeV_IR_obj
    
    elif (Ne_IR_Fq[0] in Fr or Ne_IR_Fq[1] in Fr) and Ne_IR_Fq[4] in Fr:
        print(f"{ind}, {name}, NeII and NeIII")
        #Writing the object names
        outstring = [name,df['Id_used_NED'][ind],df['RA'][ind],df['DEC'][ind],df['otype_txt'][ind],df['redshift'][ind],
                     df['rvz_type'][ind],df['otypes'][ind],'NeII|NeIII',df['SMB_sample'][ind]]
        writer.writerow(outstring) #write the data
        NeII_NeIII_IR_obj.append(name) #Save the object name in the list NeII_NeIII_IR_obj
    
    elif (Ne_IR_Fq[2] in Fr or Ne_IR_Fq[3] in Fr) and Ne_IR_Fq[4] in Fr:
        print(f"{ind}, {name}, NeII and NeV")
        #Writing the object names
        outstring = [name,df['Id_used_NED'][ind],df['RA'][ind],df['DEC'][ind],df['otype_txt'][ind],df['redshift'][ind],
                     df['rvz_type'][ind],df['otypes'][ind],'NeII|NeV',df['SMB_sample'][ind]]
        writer.writerow(outstring) #write the data
        NeII_NeV_IR_obj.append(name) #Save the object name in the list NeII_NeV_IR_obj
    
    elif (Ne_IR_Fq[0] in Fr or Ne_IR_Fq[1] in Fr) and (Ne_IR_Fq[2] in Fr or Ne_IR_Fq[3] in Fr):
        print(f"{ind}, {name}, NeIII and NeV")
        #Writing the object names
        outstring = [name,df['Id_used_NED'][ind],df['RA'][ind],df['DEC'][ind],df['otype_txt'][ind],df['redshift'][ind],
                     df['rvz_type'][ind],df['otypes'][ind],'NeIII|NeV',df['SMB_sample'][ind]]
        writer.writerow(outstring) #write the data
        NeIII_NeV_IR_obj.append(name) #Save the object name in the list NeIII_NeV_IR_obj
    
    elif Ne_IR_Fq[0] in Fr or Ne_IR_Fq[1] in Fr:
        print(f"{ind}, {name}, NeIII")
        #Writing the object names
        outstring = [name,df['Id_used_NED'][ind],df['RA'][ind],df['DEC'][ind],df['otype_txt'][ind],df['redshift'][ind],
                     df['rvz_type'][ind],df['otypes'][ind],'NeIII',df['SMB_sample'][ind]]
        writer.writerow(outstring) #write the data
        NeIII_IR_obj.append(name) #Save the object name in the list NeIII_IR_obj
    
    elif Ne_IR_Fq[2] in Fr or Ne_IR_Fq[3] in Fr:
        print(f"{ind}, {name}, NeV")
        #Writing the object names
        outstring = [name,df['Id_used_NED'][ind],df['RA'][ind],df['DEC'][ind],df['otype_txt'][ind],df['redshift'][ind],
                     df['rvz_type'][ind],df['otypes'][ind],'NeV',df['SMB_sample'][ind]]
        writer.writerow(outstring) #write the data
        NeV_IR_obj.append(name) #Save the object name in the list NeV_IR_obj
   
    elif Ne_IR_Fq[4] in Fr:
        print(f"{ind}, {name}, NeII")
        #Writing the object names
        outstring = [name,df['Id_used_NED'][ind],df['RA'][ind],df['DEC'][ind],df['otype_txt'][ind],df['redshift'][ind],
                     df['rvz_type'][ind],df['otypes'][ind],'NeII',df['SMB_sample'][ind]]
        writer.writerow(outstring) #write the data
        NeII_IR_obj.append(name) #Save the object name in the list NeII_IR_obj

end = time.time()

#we close the file with objects names
outfile.close()

print('\nTotal objects found with NeII, NeIII and NeV emission lines: ',len(NeII_NeIII_NeV_IR_obj))
print('Total objects found with NeII and NeIII emission lines: ',len(NeII_NeIII_IR_obj))
print('Total objects found with NeII and NeV emission lines: ',len(NeII_NeV_IR_obj))
print('Total objects found with NeIII and NeV emission lines: ',len(NeIII_NeV_IR_obj))
print('Total objects found with NeIII emission lines: ',len(NeIII_IR_obj))
print('Total objects found with NeV emission lines: ',len(NeV_IR_obj))
print('Total objects found with NeII emission lines: ',len(NeII_IR_obj))
print('\nExecution Time(seg): ' + str(end - start))
print('Execution Time(min): ' + str((end - start)/60))
print('Execution Time(hrs): ' + str((end - start)/3600))

0, 3C 234.0, NeII, NeIII and NeV
1, M  84, NeV
2, 2MASS J13000535+1632148, NeII, NeIII and NeV
3, NGC   262, NeII, NeIII and NeV
4, IRAS 04385-0828, NeII, NeIII and NeV
5, NGC  4945, NeII, NeIII and NeV
6, IC 4553, NeII, NeIII and NeV
7, NGC  5252, NeII
8, Mrk  279, NeII, NeIII and NeV
9, UGC 11680, NeII
10, LEDA   45656, NeII and NeV
11, Mrk 1239, NeII, NeIII and NeV
12, LEDA   89032, NeII, NeIII and NeV
13, NAME 3C 330G2, NeII, NeIII and NeV
14, 3C 265.0, NeII, NeIII and NeV
15, NGC   612, NeII
16, NGC  7479, NeII, NeIII and NeV
17, LEDA 3095998, NeII
18, NGC  3735, NeII, NeIII and NeV
19, NGC  4477, NeII, NeIII and NeV
20, LEDA   89511, NeII, NeIII and NeV
21, NGC   185, NeV
22, 2MASS J00105486+0014510, NeIII
23, Z 218-7, NeII, NeIII and NeV
24, Mrk  493, NeII, NeIII and NeV
25, NGC  4941, NeII, NeIII and NeV
26, Mrk  883, NeII and NeIII
27, 2MASS J22255427+1958370, NeII, NeIII and NeV
28, LEDA   90196, NeII, NeIII and NeV
29, MCG+04-48-002, NeII, NeIII and NeV
30, [VV2000] J235225.0+244009, NeII, NeIII and NeV
31, 3C 196, NeII, NeIII and NeV
32, 2MASX J10032788+5541535, NeV
33, NGC  2622, NeII, NeIII and NeV
34, NGC   863, NeII, NeIII and NeV
35, [VV2003c] J005439.8+155446, NeIII
36, IRAS 11215-2806, NeII, NeIII and NeV
37, 2MASS J15011320+2329082, NeII and NeV
38, NGC  3281, NeII, NeIII and NeV
39, ESO 323-32, NeII
40, LEDA  101275, NeII, NeIII and NeV
41, NAME Circinus Galaxy, NeII, NeIII and NeV
42, IC 3639, NeII, NeIII and NeV
43, Mrk  926, NeII, NeIII and NeV
44, Mrk  463E, NeII, NeIII and NeV
45, NGC  4235, NeII, NeIII and NeV
46, IRAS 15480-0344, NeII, NeIII and NeV
47, UGC  6728, NeII, NeIII and NeV
48, NGC  1142, NeII, NeIII and NeV
49, NGC  1365, NeII, NeIII and NeV
50, NGC  1056, NeII, NeIII and NeV
51, NGC  7410, NeII and NeV
52, Mrk  352, NeII, NeIII and NeV
53, LEDA 1365424, NeII, NeIII and NeV
54, LEDA   27453, NeIII
55, NAME Cyg A, NeII, NeIII and NeV
56, Mrk  877, NeII and NeV
57, ESO 148-2, NeII, NeIII and NeV
58, Mrk 1383, NeII, NeIII and NeV
59, NGC  7592, NeV
60, NGC  3998, NeII, NeIII and NeV
61, QSO B1626+5529, NeII, NeIII and NeV
62, Mrk    9, NeII, NeIII and NeV
63, Mrk 1513, NeII, NeIII and NeV
64, NGC  4939, NeII, NeIII and NeV
65, NGC  4151, NeII, NeIII and NeV
66, [VV2003c] J035734.0-053719, NeIII
67, ESO 434-40, NeII, NeIII and NeV
68, LEDA   37102, NeII, NeIII and NeV
69, ESO 323-77, NeII, NeIII and NeV
70, FRL   49, NeII, NeIII and NeV
71, LEDA   50824, NeII, NeIII and NeV
72, LEDA   29208, NeII and NeV
73, NGC    34, NeII, NeIII and NeV
74, SWIFT J0624.1-6059, NeII
75, NGC  2685, NeV
76, ESO 198-24, NeII
77, Mrk  471, NeII, NeIII and NeV
78, NGC  7679, NeII, NeIII and NeV
79, SDSS J143417.15+020742.3, NeIII
80, IRAS 11119+3257, NeII, NeIII and NeV
81, IC 1065, NeII, NeIII and NeV
82, 2MASX J14305363+3458364, NeII
83, M  81, NeII, NeIII and NeV
84, 2MASS J14533151+1353587, NeII, NeIII and NeV
85, NGC  2639, NeII, NeIII and NeV
86, NGC   513, NeII, NeIII and NeV
87, NAME IRAS F15163+4255 NW, NeII, NeIII and NeV
88, ESO 383-35, NeII, NeIII and NeV
89, NAME IRAS 09111-1007W, NeV
90, NGC   973, NeII, NeIII and NeV
91, 2E  3648, NeII, NeIII and NeV
92, Mrk  937, NeII
93, SDSS J040208.86-050642.0, NeIII
94, 2MASX J22041914+0333511, NeII, NeIII and NeV
95, 2XMM J094046.2+033929, NeV
96, NGC  7469, NeII, NeIII and NeV
97, IRAS F08216+3009, NeII, NeIII and NeV
98, 2MASX J08035923+2345201, NeII, NeIII and NeV
99, NGC  7591, NeII, NeIII and NeV
100, 2MASS J08105865+7602424, NeII, NeIII and NeV
101, LEDA  166692, NeII, NeIII and NeV
102, IRAS 15091-2107, NeII, NeIII and NeV
103, 2MASS J14025120+2631175, NeII, NeIII and NeV
104, [VV2010c] J221452.9+135118, NeV
105, UGC 12282, NeII, NeIII and NeV
106, 2MASS J14294306+4747262, NeII
107, MCG+10-17-021, NeII, NeIII and NeV
108, ESO 113-45, NeII, NeIII and NeV
109, NGC  4388, NeII, NeIII and NeV
110, NGC  5899, NeII, NeIII and NeV
111, LEDA 3096524, NeII, NeIII and NeV
112, NGC  5728, NeII, NeIII and NeV
113, ESO 140-43, NeII, NeIII and NeV
114, IC 1816, NeII, NeIII and NeV
115, SDSS J161647.32+371621.2, NeII, NeIII and NeV
116, ESO 417-6, NeII, NeIII and NeV
117, NGC   788, NeII, NeIII and NeV
118, 2C 1066, NeII, NeIII and NeV
119, IC 5298, NeV
120, IC 5063, NeII, NeIII and NeV
121, PB  3894, NeII, NeIII and NeV
122, M  88, NeII, NeIII and NeV
123, NGC  4602, NeII and NeV
124, IRAS 13342+3932, NeII, NeIII and NeV
125, NGC  1241, NeII, NeIII and NeV
126, NGC  4138, NeII, NeIII and NeV
127, NGC  1566, NeII, NeIII and NeV
128, NGC  1808, NeII, NeIII and NeV
129, ICRF J054236.1+495107, NeII, NeIII and NeV
130, NGC  4074, NeII
131, Mrk  304, NeII, NeIII and NeV
132, Mrk 1298, NeII and NeV
133, 2XMM J135315.8+634546, NeII, NeIII and NeV
134, Mrk 1095, NeII, NeIII and NeV
135, IRAS 15206+3342, NeII, NeIII and NeV
136, 2E   437, NeII
137, 2MASS J10520202+5633010, NeII and NeIII
138, 2MASX J14510879+2709272, NeII and NeV
139, IC  486, NeII, NeIII and NeV
140, ATO J176.4186-18.4541, NeII
141, Mrk  618, NeII, NeIII and NeV
142, NGC  5273, NeII, NeIII and NeV
143, Mrk  609, NeII, NeIII and NeV
144, NGC  3079, NeII, NeIII and NeV
145, LEDA  165618, NeII, NeIII and NeV
146, IRAS 03450+0055, NeII, NeIII and NeV
147, 3C 343.1, NeII, NeIII and NeV
148, 2C   94, NeII, NeIII and NeV
149, Ton  182, NeII
150, MCG+13-07-002, NeII, NeIII and NeV
151, Ton  1388, NeII and NeV
152, NGC  5548, NeII, NeIII and NeV
153, ICRF J145907.5+714019, NeII, NeIII and NeV
154, NGC   424, NeII, NeIII and NeV
155, Mrk  509, NeII, NeIII and NeV
156, ESO   5-4, NeII, NeIII and NeV
157, NGC   660, NeII, NeIII and NeV
158, NGC  4355, NeII
159, NGC  2992, NeII, NeIII and NeV
160, ESO 141-55, NeII, NeIII and NeV
161, Mrk  334, NeII, NeIII and NeV
162, NGC  1204, NeII, NeIII and NeV
163, [VV2003c] J135355.9+664800, NeIII
164, Mrk 1502, NeII, NeIII and NeV
165, 2XMM J101756.8+390526, NeV
166, 2XMM J142930.6+425148, NeV
167, NGC  7314, NeII, NeIII and NeV
168, ESO 420-13, NeII and NeV
169, UGC  1395, NeII, NeIII and NeV
170, IC 4518A, NeII, NeIII and NeV
171, NAME Centaurus A, NeII, NeIII and NeV
172, 2XMM J094506.4+035552, NeV
173, ICRF J052109.8+163822, NeII, NeIII and NeV
174, IRAS 17002+5153, NeII and NeV
175, ESO 506-27, NeII
176, Z  41-20, NeII
177, Mrk  771, NeII, NeIII and NeV
178, 3C 295, NeII
179, Mrk  876, NeII, NeIII and NeV
180, Mrk 1014, NeII, NeIII and NeV
181, Mrk 1457, NeII, NeIII and NeV
182, Mrk  573, NeII, NeIII and NeV
183, ESO 428-14, NeII, NeIII and NeV
184, UGC  1841, NeV
185, M  49, NeV
186, ESO 263-13, NeII
187, 2MASX J21564950-0745325, NeV
188, LEDA 2816291, NeIII
189, ICRF J090933.4+425346, NeII, NeIII and NeV
190, NGC  5347, NeII, NeIII and NeV
191, Mrk  520, NeII
192, NGC  4748, NeII, NeIII and NeV
193, NGC  1667, NeII, NeIII and NeV
194, 2C 1883, NeII, NeIII and NeV
195, NGC  1320, NeII, NeIII and NeV
196, Mrk 1073, NeII, NeIII and NeV
197, NGC  6300, NeII, NeIII and NeV
198, NGC  5643, NeII, NeIII and NeV
199, NGC  2273, NeII, NeIII and NeV
200, 2MASS J00070361+1554238, NeII, NeIII and NeV
201, NGC  7172, NeII, NeIII and NeV
202, NGC  3393, NeIII and NeV
203, ESO 209-12, NeII
204, 2MASX J10181928+3722419, NeII, NeIII and NeV
205, LEDA   52314, NeII and NeV
206, SDSS J032845.99+011150.8, NeIII
207, NGC   931, NeII, NeIII and NeV
208, 2MASS J13234951+6541480, NeII
209, Mrk  335, NeII, NeIII and NeV
210, NGC  3976, NeII, NeIII and NeV
211, Ton  951, NeV
212, M  58, NeII, NeIII and NeV
213, 2dFGRS TGN336Z243, NeV
214, LEDA 1487448, NeII, NeIII and NeV
215, NGC  4395, NeII, NeIII and NeV
216, MCG+00-25-010, NeII and NeIII
217, LEDA    3237, NeII
218, NGC  6890, NeII, NeIII and NeV
219, 2MASX J14254352+3345275, NeII and NeIII
220, LEDA    1790, NeII, NeIII and NeV
221, 3C  84, NeII, NeIII and NeV
222, LEDA 2149945, NeII
223, NGC  7743, NeII, NeIII and NeV
224, Mrk   22, NeII and NeIII
225, LEDA   90127, NeII, NeIII and NeV
226, ESO 445-50, NeII, NeIII and NeV
227, 2MASS J16370022+2221140, NeII, NeIII and NeV
228, Mrk  817, NeII, NeIII and NeV
229, IC 3078, NeIII
230, NGC  6810, NeII, NeIII and NeV
231, 2MASS J21035875-0728025, NeIII
232, Mrk  273, NeII, NeIII and NeV
233, LEDA   90429, NeII, NeIII and NeV
234, ICRF J134733.3+121724, NeII, NeIII and NeV
235, NGC  3367, NeV
236, ESO 362-18, NeII, NeIII and NeV
237, IC  450, NeII, NeIII and NeV
238, NGC  6951, NeII, NeIII and NeV
239, MCG-02-08-039, NeII, NeIII and NeV
240, 2C  349, NeV
241, NGC  7674, NeII, NeIII and NeV
242, NGC  6221, NeII, NeIII and NeV
243, ESO  12-21, NeII, NeIII and NeV
244, UGC  5101, NeII, NeIII and NeV
245, ESO 602-25, NeII, NeIII and NeV
246, ESO 511-30, NeII
247, MCG-03-34-064, NeII, NeIII and NeV
248, NGC  3516, NeII, NeIII and NeV
249, NGC  4593, NeII, NeIII and NeV
250, UGC  7064, NeII and NeIII
251, NGC  5135, NeII, NeIII and NeV
252, Mrk  231, NeII, NeIII and NeV

253, Mrk   79, NeII, NeIII and NeV
254, LEDA   68751, NeII, NeIII and NeV
255, NGC  7319, NeIII and NeV
256, Mrk  863, NeIII
257, 2MASX J18334627+4727027, NeII, NeIII and NeV
258, Mrk 1066, NeII, NeIII and NeV
259, ESO 253-3, NeII, NeIII and NeV
260, 2MASS J01083516+2148186, NeII, NeIII and NeV
261, 3C  22.0, NeII, NeIII and NeV
262, 2MASX J14304627+3513133, NeII and NeIII
263, Ton  1565, NeII and NeV
264, Mrk  704, NeII, NeIII and NeV
265, NGC  6240, NeII, NeIII and NeV
266, ESO 121-28, NeII
267, NGC  7603, NeII, NeIII and NeV
268, UGC 12138, NeII, NeIII and NeV
269, ESO 339-11, NeV
270, NGC  1058, NeII and NeV
271, IC 2560, NeII, NeIII and NeV
272, QSO B1048+342, NeII
273, NGC  1125, NeII and NeIII
274, LEDA   24384, NeII and NeIII
275, M 106, NeII, NeIII and NeV
276, NGC  5995, NeII, NeIII and NeV
277, 2MASSI J0918486+211717, NeII, NeIII and NeV
278, LEDA   17155, NeII, NeIII and NeV
279, [VV2003c] J082001.7+505039, NeIII
280, 2MASX J08584172+1041223, NeII, NeIII and NeV
281, SDSS J231812.99-004126.1, NeIII
282, 3C 343, NeII, NeIII and NeV
283, NGC  4992, NeII
284, NGC  5395, NeV
285, 2MASS J10272497+1219196, NeII, NeIII and NeV
286, M  94, NeII, NeIII and NeV
287, NGC  5990, NeII, NeIII and NeV
288, Mrk    3, NeII, NeIII and NeV
289, NGC  4051, NeII, NeIII and NeV
290, LEDA   70560, NeII, NeIII and NeV
291, 3C 452, NeII, NeIII and NeV
292, LEDA  165630, NeII, NeIII and NeV
293, MCG+00-29-023, NeII, NeIII and NeV
294, 4C 23.43, NeII, NeIII and NeV
295, UGC  3351, NeII, NeIII and NeV
296, Mrk  705, NeII, NeIII and NeV
297, UGC  3601, NeII, NeIII and NeV
298, 3C 286, NeII, NeIII and NeV
299, ESO  33-2, NeII, NeIII and NeV
300, NGC  4725, NeII, NeIII and NeV
301, NGC  7682, NeII, NeIII and NeV
302, [VV2003c] J124819.8+662143, NeIII
303, 7C 1821+6419, NeII, NeIII and NeV
304, MCG-01-24-012, NeII, NeIII and NeV
305, NGC  1358, NeII, NeIII and NeV
306, NGC  2110, NeII, NeIII and NeV
307, 2MASS J10514425+3539307, NeII, NeIII and NeV
308, NGC  5929, NeII, NeIII and NeV
309, SDSS J120424.54+192509.7, NeII, NeIII and NeV
310, ESO 297-18, NeII
311, NGC  4968, NeII, NeIII and NeV
312, NGC   253, NeII, NeIII and NeV
313, NGC  3660, NeII, NeIII and NeV
314, NAME Pic A, NeII
315, NGC  6926, NeV
316, 2E  2389, NeII and NeV
317, ESO 103-35, NeII, NeIII and NeV
318, ICRF J182931.7+484446, NeII, NeIII and NeV
319, 2MASX J12390630-1610472, NeII
320, NGC  5033, NeII, NeIII and NeV
321, MCG-03-58-007, NeII, NeIII and NeV
322, 2E  2503, NeII, NeIII and NeV
323, NGC  4922, NeII, NeIII and NeV
324, LEDA   90054, NeV
325, PG 0953+414, NeII and NeV
326, IRAS F15146+1911, NeII, NeIII and NeV
327, 2MASX J12135486+0247529, NeV
328, NGC  1194, NeII, NeIII and NeV
329, NGC  6814, NeII, NeIII and NeV
330, ICRF J015002.6-072548, NeII, NeIII and NeV
331, Mrk  463, NeV
332, ICRF J130533.0-103319, NeII, NeIII and NeV
333, Z 121-75, NeII, NeIII and NeV
334, Mrk  841, NeII, NeIII and NeV
335, NGC  3147, NeII, NeIII and NeV
336, LEDA   75476, NeII, NeIII and NeV
337, LEDA 2817285, NeII, NeIII and NeV
338, NGC  7213, NeII, NeIII and NeV
339, Mrk 1506, NeII, NeIII and NeV
340, IRAS F00183-7111, NeII, NeIII and NeV
341, LBQS 1244+0238, NeII and NeV
342, NGC  6860, NeII, NeIII and NeV
343, LEDA  178130, NeII
344, 4C 13.41, NeII and NeV
345, NGC  4253, NeII, NeIII and NeV
346, Mrk  478, NeII, NeIII and NeV
347, IRAS 07598+6508, NeII
348, 2MASS J10434845+5811477, NeII and NeIII
349, NGC  3081, NeII, NeIII and NeV
350, NGC  4507, NeII, NeIII and NeV
351, 2XMM J115657.8+550820, NeV
352, 2MASX J00215355-7910077, NeII, NeIII and NeV
353, NGC  3783, NeII, NeIII and NeV
354, NGC  3982, NeII, NeIII and NeV
355, PSCz Q18368+3549, NeII, NeIII and NeV
356, Mrk  622, NeII, NeIII and NeV
357, [LGE2006] 12, NeIII
358, 2MASX J14323249+3406257, NeII and NeIII

Total objects found with NeII, NeIII and NeV emission lines:  253
Total objects found with NeII and NeIII emission lines:  11
Total objects found with NeII and NeV emission lines:  18
Total objects found with NeIII and NeV emission lines:  2
Total objects found with NeIII emission lines:  16
Total objects found with NeV emission lines:  26
Total objects found with NeII emission lines:  33

Execution Time(seg): 3.855205774307251
Execution Time(min): 0.06425342957178752
Execution Time(hrs): 0.0010708904928631252

In [18]:
df2 = pd.read_csv(path_raw+'Obj_Ne-IR_v2_'+date_samples+'.csv')
df2

,Name_Id,id_from,RA,DEC,otype_txt,redshift,rvz_type,otypes,Ne_IR_info,SMB_sample
0,3C 234.0,3C 234.0,150.456345,28.785818,Sy1,0.18494,z,AGN|G |IR |QSO|Rad|Sy1|X |blu|gam,NeII|NeIII|NeV,283
1,M 84,M 84,186.265597,12.886983,Sy2,0.00327,z,* |AGN|G |GiC|GiG|IR |Rad|Sy2|UV |X |smm,NeV,414
2,2MASS J13000535+1632148,NVSS J130005+163212,195.022283,16.537433,Sy1,0.07993,z,AGN|G |IR |Rad|Sy1|X,NeII|NeIII|NeV,428
3,NGC 262,NGC 262,12.196426,31.956957,Sy2,0.015260233939595302,v,* |AGN|Bla|G |GiG|IR |QSO|Rad|Sy2|X |gam,NeII|NeIII|NeV,484
4,IRAS 04385-0828,IRAS 04385-0828,70.229004,-8.372813,Sy2,0.015064,z,* |AGN|G |GiG|IR |Sy2,NeII|NeIII|NeV,541
...,...,...,...,...,...,...,...,...,...,...
354,NGC 3982,NGC 3982,179.117269,55.125239,Sy1,0.00371,z,AGN|G |GiG|HI |IR |Rad|Sy1|X,NeII|NeIII|NeV,43595
355,PSCz Q18368+3549,IRAS 18368+3549,279.647646,35.872153,Sy2,0.11617,z,AGN|G |IR |Mas|Sy2,NeII|NeIII|NeV,43670
356,Mrk 622,Mrk 622,121.920816,39.004235,Sy2,0.02335,z,AGN|G |IR |LIN|Rad|Sy2|X,NeII|NeIII|NeV,43765
357,[LGE2006] 12,[LGE2006] 12,163.000458,57.406528,Sy1,0.974,z,AGN|G |IR |Rad|Sy1|X |smm,NeIII,43819
358,2MASX J14323249+3406257,2MASX J14323249+3406257,218.135416,34.107058,Sy2,0.0424,z,* |AG?|AGN|EmG|G |Sy2,NeII|NeIII,44215

### Watermark

In [12]:
%load_ext watermark
%watermark -a "Jonhatan Bernal" -d -v -m
print('Specific Python packages')
%watermark -iv -w --packages astropy

Author: Jonhatan Bernal

Python implementation: CPython
Python version       : 3.9.7
IPython version      : 7.31.1

Compiler    : GCC 7.5.0
OS          : Linux
Release     : 5.13.0-30-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 8
Architecture: 64bit

Specific Python packages
astropy: 5.0

astropy: 5.0
pandas : 1.4.1
numpy  : 1.20.3
csv    : 1.0

Watermark: 2.3.0